### PR TITLE
Fix: Allow disabling all danmaku sources

### LINKED ISSUE #2602: 弹幕源无法全部禁用
### 问题描述

想对比一下弹幕量，所以就想先禁用所有的弹幕源，然后一个个看。但是发现禁用最后一个弹幕源之后又会把所有弹幕源都启用，相当奇怪且反直觉：

https://github.com/user-attachments/assets/f303d8f6-b183-4136-946a-6fb00c43c304

### 复现步骤

_No response_

### Ani 版本号

5.1a2

### 操作系统

Windows

### 应用日志

...

### PR DESCRIPTION
**Pull request by GeneralK1ng**
## What
Added a flag to prevent automatic re-enabling of danmaku sources when users manually disable all of them.

## Why
Previously, when users tried to disable all danmaku sources, the system would automatically re-enable them. This happened because the initialization logic couldn't distinguish between "first-time initialization" and "user manually disabled all sources". The condition `selectedDanmakuSources.value.isEmpty()` would trigger every time the set became empty, causing unwanted auto-enabling behavior.

## Where
- `EpisodeViewModel.kt`: Added `danmakuSourcesInitialized` flag to track initialization state
- Modified the danmaku source initialization logic in the `init` block to only auto-enable sources on first load

## Closes
#2602

### CODE REVIEW

**Comment by Him188** [comment]
为什么这可以修复问题

**Comment by GeneralK1ng** [comment]
当用户禁用最后一个弹幕源时，会重新触发弹幕源初始化。
添加一个标志位用以保证只加载一次

**Comment by Him188** [comment]
禁用弹幕源不应该触发初始化吧，应该是别的地方有问题

File: app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt [hunk 1]
```diff
@@ -592,12 +592,14 @@ class EpisodeViewModel(
...
     init {
         launchInBackground {
             danmakuLoader.fetchResults.collect { fetchResults ->
                 val availableSources = fetchResults.map { it.serviceId }.toSet()
-                if (availableSources.isNotEmpty() && selectedDanmakuSources.value.isEmpty()) {
+                if (availableSources.isNotEmpty() && selectedDanmakuSources.value.isEmpty() && !danmakuSourcesInitialized) {
+                    danmakuSourcesInitialized = true
                     selectedDanmakuSources.value = availableSources
                     // Enable all sources by default
                     availableSources.forEach { serviceId ->
```
Comment (Him188) [inline app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt]: 看起来不应该有这个逻辑

**Comment by StageGuard** [comment]
> 当用户禁用最后一个弹幕源时，会重新触发弹幕源初始化。 添加一个标志位用以保证只加载一次

那应该修复不让弹幕源初始化，现在的修复看起来就是在 workaround 堆史

**Comment by GeneralK1ng** [comment]
`DanmakuOriginConfig` 中的 `enable`变化导致重复初始化，现在只关心源列表的更新

File: app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt [hunk 2]
```diff
@@ -578,33 +578,35 @@ class EpisodeViewModel(
...
-            danmakuLoader.fetchResults.collect { fetchResults ->
-                val availableSources = fetchResults.map { it.serviceId }.toSet()
-                if (availableSources.isNotEmpty() && selectedDanmakuSources.value.isEmpty()) {
-                    selectedDanmakuSources.value = availableSources
-                    // Enable all sources by default
-                    availableSources.forEach { serviceId ->
-                        setDanmakuSourceEnabled(serviceId, true)
+            // 只在源列表变化时初始化，而不是配置变化时 #2602
+            danmakuLoader.fetchResults
+                .map { results -> results.map { it.serviceId }.toSet() }
```
Comment (Him188) [inline app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt]:
```suggestion
                .map { results -> results.mapTo(mutableSetOf()) { it.serviceId } }
```

**Review by Him188 — COMMENTED** [review]
其实整个弹幕逻辑应该是默认开启, 有个 `private val disabledDanmakuSources` 吧

现在的写法感觉绕了一圈

**Comment by GeneralK1ng** [comment]
抱歉延迟修复，现在用`DanmakuListStateProducer`直接获取状态

**Comment by StageGuard** [comment]
Can I merge?

**Comment by GeneralK1ng** [comment]
> Can I merge?

Sure, i have tested this.
